export const ALERT_CATEGORIES = {
  "Board Meeting": [
    "Board Meeting",
    "Committee Meeting",
    "Outcome of Board Meeting"
  ],
  "Result": [
    "Auditors Report",
    "Change in Accounting Year",
    "Financial Results",
    "Limited Review Report"
  ],
  "AGM/EGM": [
    "AGM",
    "Book Closure / AGM",
    "Court Convened Meeting",
    "EGM",
    "Postal Ballot"
  ],
  "Company Update": [
  "Acquisition",
  "Admission of application by Tribunal",
  "Adoption of new line(s) of business (Sub-para 2-Para B)",
  "Agreement",
  "Agreements (Sub-para 5-Para B)",
  "Agreements, Contracts, Arrangements, MOU",
  "Allotment of Equity Shares",
  "Allotment of ESOP / ESPS",
  "Allotment of Warrants",
  "Allotment of shares",
  "Alteration of Capital",
  "Amalgamation/ Merger",
  "Amendment or termination of orders/contracts (Sub-para 4-Para B)",
  "Amendments to Memorandum & Articles of Association",
  "Analyst/Investor Meet",
  "Analysts/Institutional Investors Meet",
  "Announcement under Regulation 30",
  "Annual Disclosure - Investor Complaints",
  "Annulment / Re-issue of forfeited shares",
  "Appointment of Chairman",
  "Appointment of Chairman and Managing Director",
  "Appointment of Chief Executive Officer (CEO)",
  "Appointment of Chief Financial Officer (CFO)",
  "Appointment of Company Secretary / Compliance Officer",
  "Appointment of Director",
  "Appointment of Interim Resolution Professional (IRP)",
  "Appointment of Managing Director",
  "Appointment of Managing Director & CEO",
  "Appointment of Statutory Auditor/s",
  "Approval of Resolution plan by Tribunal",
  "Arrangements (Sub-para 2-Para B)",
  "Award of Order / Receipt of Order",
  "Awarding of order(s)/contract(s) (Sub-para 4-Para B)",
  "Bagging/Receiving of orders/contracts (Sub-para 4-Para B)",
  "Board Meeting Adjourned",
  "Board Meeting Cancelled",
  "Board Meeting Deferred",
  "Board Meeting Postponed",
  "Board Meeting Rescheduled",
  "Buy back",
  "Cancellation of Dividend",
  "Capacity addition (Sub-para 3-Para B)",
  "Certificate",
  "Certificate under Reg. 74 (5) of SEBI (DP) Regulations, 2018",
  "Cessation",
  "Change in Auditors",
  "Change in Corporate Office Address",
  "Change in Directorate",
  "Change in Directors/ Key Managerial Personnel/ Auditor/ Compliance Officer/ Share Transfer Agent",
  "Change in Financial Year",
  "Change in Management",
  "Change in Management Control",
  "Change in Registered Office",
  "Change in Registered Office Address",
  "Change in regulatory framework (Sub-para 7-Para B)",
  "Change of Name",
  "Clarification",
  "Clarification of News Item",
  "Closure of Buy Back",
  "Closure of operations (Sub-para 2-Para B)",
  "Closure of Trading Window",
  "Code of Conduct under SEBI (PIT) Regulations, 2015",
  "Commencement or postponement (Sub-para 1-Para B)",
  "Compliance Certificate",
  "Corporate Debt Restructuring",
  "Corporate Insolvency Resolution Process",
  "Credit Rating",
  "De-merger",
  "Debt Securities",
  "Declaration of Book Closure/ Record Date",
  "Declaration of NAV",
  "Delay or default in the payment of fines (Sub-para 13-Para B)",
  "Delisting",
  "Demise",
  "Disclosure of IDR Holding",
  "Disclosure under Clause 35A of the Listing Agreement",
  "Disclosures",
  "Disruption of operations (Sub-para 6-Para B)",
  "Diversification / Disinvestment",
  "Earnings Call Transcript",
  "FCCBS",
  "Filing of Resolution plan with Tribunal",
  "Frauds/defaults/arrest - employee (Sub-para 9-Para B)",
  "Funds raising by issuance of Debt Securities by Large Entities",
  "General",
  "Giving of guarantees or indemnity (Sub-para 11-Para B)",
  "Impact of Audit Qualifications",
  "Incorporation",
  "Increase of Authorised Capital",
  "Initiation of Corporate Insolvency Resolution Process (CIRP) by Corporate Applicant",
  "Initiation of Corporate Insolvency Resolution Process (CIRP) by Financial Creditors",
  "Institutional Placement Programme",
  "Intimation of meeting of Committee of Creditors",
  "Intimation on Agreements",
  "Intimation on Fraud",
  "Intimation on OTS and Restructuring Loans or Borrowings",
  "Investor Presentation",
  "Invitation of Resolution Plan",
  "Issue of Securities",
  "Joint Venture",
  "Key licenses/regulatory approvals (Sub-para 12-Para B)",
  "Liquidation - Corporate Insolvency Resolution Process (CIRP)",
  "List of Creditors",
  "Loss of Share Certificate and Issue of Duplicate Share Certificate or Letter of Confirmation",
  "Meeting Updates",
  "Memorandum of Understanding /Agreements",
  "Monitoring Agency Report",
  "Monthly AUM Disclosure",
  "Monthly Business Updates",
  "NAV Declaration",
  "NCLT/ Court Convened Meeting",
  "Newspaper Publication",
  "Notice Of Shareholders Meetings - Annual General Meeting",
  "Notice Of Shareholders Meetings - Extra-ordinary Meeting",
  "Notice Of Shareholders Meetings - NCLT/ Court Convened Meeting",
  "Notice Of Shareholders Meetings - Postal Ballot",
  "Offer for Sale",
  "Open Offer",
  "Open Offer - Updates",
  "Options to purchase securities ESOPS (Sub-para 10-Para B)",
  "Other Restructuring",
  "Others",
  "Outcome of meeting of Committee of Creditors",
  "Pendency of any litigation(s) or dispute(s) (Sub-para 8-Para B)",
  "Post Buyback Public Announcement",
  "Post Offer Public Announcement",
  "Preferential Issue",
  "Press release (Revised)",
  "Press Release / Media Release",
  "Press Release / Media Release (Revised)",
  "Product launch (Sub-para 3-Para B)",
  "Public Announcement",
  "Public Announcement-Buyback of Shares",
  "Public Announcement-Delisting",
  "Public Announcement-Open Offer",
  "Qualified Institutional Placement",
  "Quarterly AUM Disclosure",
  "Raising of Funds",
  "Reg. 13(3) Statement of Investor Complaints",
  "Reg. 30 Awarding of orders/contracts",
  "Reg. 32 (1), (3) - Statement of Deviation & Variation",
  "Reg. 40 (10) - PCS Certificate for Transfer / Transmission / Transposition",
  "Reg. 7(3) - Compliance Certificate (RTA & Compliance Officer)",
  "Reg.24(A)-Annual Secretarial Compliance",
  "Rejection of Resolution pan by Tribunal",
  "Replacement of Interim Resolution Professional (IRP)",
  "Resignation of Chairman",
  "Resignation of Chairman and Managing Director",
  "Resignation of Chief Executive Officer (CEO)",
  "Resignation of Chief Financial Officer (CFO)",
  "Resignation of Company Secretary / Compliance Officer",
  "Resignation of Director",
  "Resignation of Managing Director",
  "Resignation of Statutory Auditors",
  "Resolution Plans received by Resolution Professional",
  "Restructuring",
  "Retirement",
  "Revision of outcome",
  "Sale of shares",
  "Sale or disposal",
  "Scheme of Arrangement",
  "Shareholding pattern",
  "Shareholding Slump Sale",
  "Statement of Investor Complaint",
  "Strike",
  "Strikes/Lockouts / Disturbances",
  "Trading Plan under SEBI (PIT) Regulations, 2015",
  "Update-Acquisition/Scheme/Sale/Disposal/Reg30",
  "Updates - Corporate Insolvency Resolution Process (CIRP)",
  "Utilisation of Funds",
  "Voluntary Delisting",
  "Winding-up"
  ],
  "Corp. Action": [
    "Amalgamation / Merger / Demerger",
    "Bonds / Right issue",
    "Bonus",
    "Book Closure",
    "Capital Reduction",
    "Consolidation of Shares",
    "Dividend",
    "Record Date",
    "Sub-division / Stock Split"
  ],
  "Insider Trading / SAST": [
  "Closure of Trading Window",
  "Disclosures under Reg. 10(5) in respect of acquisition under Reg. 10(1)(a) of SEBI (SAST) Reg. 2011",
  "Disclosures under Reg. 10(5) in respect of acquisition under Reg. 10(4)(e) of SEBI (SAST) Reg. 2011",
  "Disclosures under Reg. 10(5) in respect of acquisition under Reg. 10(4)(f) of SEBI (SAST) Reg. 2011",
  "Disclosures under Reg. 10(6) of SEBI (SAST) Regulations, 2011",
  "Disclosures under Reg. 10(7) of SEBI (SAST) Regulations, 2011",
  "Disclosures under Reg. 18(6) of SEBI (SAST) Regulations, 2011",
  "Disclosures under Reg. 29(1) of SEBI (SAST) Regulations, 2011",
  "Disclosures under Reg. 29(2) of SEBI (SAST) Regulations, 2011",
  "Disclosures under Reg. 3(3) of SEBI (SAST) Regulations, 1997",
  "Disclosures under Reg. 31(1) and 31(2) of SEBI (SAST) Regulations, 2011",
  "Disclosures under Reg. 7(1) of SEBI (SAST) Regulations, 1997",
  "Disclosures under Reg. 7(1A) of SEBI (SAST) Regulations, 1997",
  "Disclosures under Reg. 7(2) read with Reg. 6(2) of SEBI (PIT) Regulations, 2015",
  "Disclosures under Reg. 7(3) of SEBI (SAST) Regulations, 1997",
  "Disclosures under Reg. 8A of SEBI (SAST) Regulations, 1997",
  "Disclosures under Reg.13(4) of SEBI (Prohibition of Insider Trading) Regulations, 1992",
  "Disclosures under Reg.13(4), 13(4A) of SEBI (Prohibition of Insider Trading) Regulations, 1992",
  "Disclosures under Reg.13(4), 13(4A) and 13(6) of SEBI (Prohibition of Insider Trading) Regulations, 1992",
  "Disclosures under Reg.13(4A) of SEBI (Prohibition of Insider Trading) Regulations, 1992",
  "Disclosures under Reg.13(6) of SEBI (Prohibition of Insider Trading) Regulations, 1992"
  ],
  "New Listing": [
    "New Listing"
  ],
  "Integrated Filing": [
    "Integrated Filing (Financial)",
    "Integrated Filing (Governance)"
  ],
  "Others": [
  "57 (4): Prior intimation to the beginning of the quarter",
  "57 (5): intimation after the end of quarter",
  "Asset Liability Management (ALM) statement",
  "Business Responsibility and Sustainability Reporting (BRSR) Certificate from CEO/CFO",
  "Certificate under Reg. 54 (5) of SEBI (DP) Regulations, 1996",
  "Compliance under Regulation 52(6) of SEBI (LODR), 2015",
  "Details of Compliance officer and RTA of the Company",
  "Disclosure of divergence in the asset classification and provisioning by banks",
  "Disclosure under Reg. 31(4) of SEBI (SAST) Regulation, 2011",
  "Disclosures by listed entities of defaults on payment of interest/repayment of principal amount for loans including revolving facilities like cash credit from banks / financial institutions.",
  "Disclosures by listed entities of defaults on payment of interest/repayment of principal amount for unlisted debt securities i.e. NCDs and NCRPS.",
  "Disclosures of reasons for encumbrance by promoter of listed companies under Reg. 31(1) read with Regulation 28(3) of SEBI (SAST) Regulations, 2011",
  "Format of the Annual Disclosure to be made by an entity identified as a Large Corporate",
  "Format of the Annual Disclosure to be made by an entity identified as a LC: Annexure B1",
  "Format of the Annual Disclosure to be made by an entity identified as a LC: Annexure B2",
  "Format of the Initial Disclosure to be made by an entity identified as a Large Corporate: Annexure A",
  "Half Yearly Communication - Debt Instruments",
  "Half Yearly Report (SEBI Circular No. CIR/IMD/DF-1/67/2017)",
  "Intimation of Repayment of Commercial Paper (CP)",
  "Mutual Fund Scheme Summary Document",
  "Outcome without intimation",
  "Quarterly Disclosures by listed entities of defaults on payment of interest/repayment of principal amount on loans from banks / financial institutions and unlisted debt securities.",
  "Record Date/Book Closure as per Regulation (60)",
  "Reg 56- Documents and Intimation to Debenture Trustee",
  "Reg. 34 (1) Annual Report",
  "Reg. 39 (3) - Details of Loss of Certificate / Duplicate Certificate",
  "Reg. 50 (1) - Prior intimation about Board meeting under Regulation 50(1)",
  "Reg. 50 (1) - Prior intimation for Interest Payment / Redemption",
  "Reg. 50 (2) - Intimation to Exchange about Intention to raise Funds",
  "Reg. 50 (2) - Intimation to the Exchange about meeting under 50(2)",
  "Reg. 50 (3) - Board Meeting Intimation",
  "Reg. 51 (1), (2) - Price Sensitive information / disclosure of event / Information",
  "Reg. 52 (5) - Certificate from Debenture Trustee",
  "Reg. 52 (7) - Statement of Material Deviations in proceeds of issue of NCD/ NCRP",
  "Reg. 52 - Declaration for Audit Report/s with Unmodified Opinion(s)",
  "Reg. 52 - Financial Result",
  "Reg. 52 - Statement of Impact on Audit Qualifications",
  "Reg. 53 - Annual Report",
  "Reg. 54 - Asset Cover details",
  "Reg. 55 - Credit Rating",
  "Reg. 57 (1) - Certificate of interest payment/Principal in case of NCD",
  "Reg. 57 (2) - Undertaking that documents & intimation submitted to Debenture trustee",
  "Reg. 59 - Prior approval from Stock Exchange for material modification in structure of NCD/ NCRP",
  "Reg. 60 (2) - Record Date - interest/dividend/redemption/repayment",
  "Reg. 7 (2) - Prohibition of Insider Trading Regulations, 2015",
  "Reg. 7 (5) - Appointment / Change of RTA",
  "Regulation 61(4) - PCS Certificate for Transfer / Transmission / Transposition"
  ]
};
