/**
 * mockData.js
 * Realistic mock announcements and watchlist entries used when the
 * backend / Firestore is not yet connected. The app falls back to
 * these so the UI looks populated during development.
 */

export const MOCK_WATCHLIST = [
  { id: 'mock-1', scriptName: 'Reliance Industries Ltd', ltdCode: '500325', exchange: 'BSE', addedAt: null, lastAnnouncementAt: null, announcementCount: 3, notes: '' },
  { id: 'mock-2', scriptName: 'Infosys Ltd', ltdCode: 'INFY', exchange: 'NSE', addedAt: null, lastAnnouncementAt: null, announcementCount: 1, notes: '' },
  { id: 'mock-3', scriptName: 'HDFC Bank Ltd', ltdCode: '500180', exchange: 'BOTH', addedAt: null, lastAnnouncementAt: null, announcementCount: 2, notes: '' },
  { id: 'mock-4', scriptName: 'Tata Consultancy Services', ltdCode: 'TCS', exchange: 'NSE', addedAt: null, lastAnnouncementAt: null, announcementCount: 0, notes: '' },
  { id: 'mock-5', scriptName: 'Wipro Ltd', ltdCode: '507685', exchange: 'BSE', addedAt: null, lastAnnouncementAt: null, announcementCount: 1, notes: '' },
  { id: 'mock-6', scriptName: 'ITC Ltd', ltdCode: '500875', exchange: 'BSE', addedAt: null, lastAnnouncementAt: null, announcementCount: 0, notes: '' },
]

const now = new Date()
function daysAgo(n) {
  const d = new Date(now)
  d.setDate(d.getDate() - n)
  return d.toISOString()
}
function hoursAgo(n) {
  const d = new Date(now)
  d.setHours(d.getHours() - n)
  return d.toISOString()
}

export const MOCK_ANNOUNCEMENTS = [
  {
    id: 'mock-ann-001',
    exchange: 'BSE',
    scriptName: 'Reliance Industries Ltd',
    scriptCode: '500325',
    category: 'Board Meeting',
    subject: 'Board of Directors Meeting scheduled for Q2 FY2026 Financial Results',
    description: 'Reliance Industries Limited has informed BSE that a meeting of the Board of Directors of the Company is scheduled on 18th October 2026 to consider and approve the Unaudited Financial Results for the quarter ended 30th September 2026.',
    announcementDate: hoursAgo(2),
    pdfUrl: null,
    sourceUrl: 'https://www.bseindia.com/corporates/ann.html',
    isWatchlisted: true,
    read: false,
  },
  {
    id: 'mock-ann-002',
    exchange: 'NSE',
    scriptName: 'Infosys Ltd',
    scriptCode: 'INFY',
    category: 'Financial Results',
    subject: 'Unaudited Financial Results for Q1 FY2026 (Standalone & Consolidated)',
    description: 'Infosys Limited has announced its unaudited financial results for the first quarter ended June 30, 2026. Revenue from operations stood at ₹38,994 crore, registering a YoY growth of 4.2%.',
    announcementDate: hoursAgo(5),
    pdfUrl: 'https://nsearchives.nseindia.com/corporate/INFY_results_q1fy26.pdf',
    sourceUrl: 'https://www.nseindia.com/companies-listing/corporate-filings-announcements',
    isWatchlisted: true,
    read: false,
  },
  {
    id: 'mock-ann-003',
    exchange: 'BSE',
    scriptName: 'HDFC Bank Ltd',
    scriptCode: '500180',
    category: 'Dividend',
    subject: 'Declaration of Interim Dividend of ₹19 per equity share for FY2026',
    description: 'HDFC Bank Limited has declared an interim dividend of ₹19/- per equity share of ₹1/- each for the financial year 2025-26. The record date for the purpose of payment of interim dividend is 8th November 2026.',
    announcementDate: daysAgo(1),
    pdfUrl: null,
    sourceUrl: 'https://www.bseindia.com/corporates/ann.html',
    isWatchlisted: true,
    read: true,
  },
  {
    id: 'mock-ann-004',
    exchange: 'NSE',
    scriptName: 'Tata Consultancy Services',
    scriptCode: 'TCS',
    category: 'Financial Results',
    subject: 'Q1 FY2026 Financial Results — PAT up 8.7% YoY to ₹12,760 crore',
    description: 'TCS reported consolidated revenue of ₹62,613 crore for Q1 FY2026, a growth of 5.4% in INR terms. Net income stood at ₹12,760 crore, up 8.7% year-on-year. The Board has declared an interim dividend of ₹10 per share.',
    announcementDate: daysAgo(1),
    pdfUrl: 'https://nsearchives.nseindia.com/corporate/TCS_results_q1fy26.pdf',
    sourceUrl: 'https://www.nseindia.com/companies-listing/corporate-filings-announcements',
    isWatchlisted: false,
    read: false,
  },
  {
    id: 'mock-ann-005',
    exchange: 'BSE',
    scriptName: 'ITC Ltd',
    scriptCode: '500875',
    category: 'AGM/EGM',
    subject: 'Notice of 113th Annual General Meeting of ITC Limited',
    description: 'ITC Limited hereby gives notice that the 113th Annual General Meeting of the Company will be held on Friday, 26th July 2026 at 10:30 A.M. (IST) through Video Conferencing (VC) / Other Audio-Visual Means (OAVM).',
    announcementDate: daysAgo(2),
    pdfUrl: null,
    sourceUrl: 'https://www.bseindia.com/corporates/ann.html',
    isWatchlisted: false,
    read: false,
  },
  {
    id: 'mock-ann-006',
    exchange: 'NSE',
    scriptName: 'Wipro Ltd',
    scriptCode: 'WIPRO',
    category: 'Merger/Acquisition',
    subject: 'Acquisition of Capco — Strengthening Financial Services Practice',
    description: 'Wipro Limited has entered into a definitive agreement to acquire Capco, a global management and technology consultancy dedicated to the financial services industry for a total consideration of USD 1.45 billion.',
    announcementDate: daysAgo(2),
    pdfUrl: 'https://nsearchives.nseindia.com/corporate/WIPRO_capco_acquisition.pdf',
    sourceUrl: 'https://www.nseindia.com/companies-listing/corporate-filings-announcements',
    isWatchlisted: true,
    read: false,
  },
  {
    id: 'mock-ann-007',
    exchange: 'BSE',
    scriptName: 'Bajaj Finance Ltd',
    scriptCode: '500034',
    category: 'Board Meeting',
    subject: 'Board Meeting to consider fund raising through issuance of NCDs',
    description: 'Bajaj Finance Limited has informed BSE that a meeting of the Board of Directors is scheduled to be held on 22nd October 2026 to consider and approve the proposal to raise funds by way of issue of Non-Convertible Debentures (NCDs) on private placement basis.',
    announcementDate: daysAgo(3),
    pdfUrl: null,
    sourceUrl: 'https://www.bseindia.com/corporates/ann.html',
    isWatchlisted: false,
    read: false,
  },
  {
    id: 'mock-ann-008',
    exchange: 'NSE',
    scriptName: 'Maruti Suzuki India Ltd',
    scriptCode: 'MARUTI',
    category: 'Financial Results',
    subject: 'Q2 FY2026 Standalone Net Profit rises 32% to ₹3,650 crore',
    description: 'Maruti Suzuki India Limited announced its standalone financial results for Q2 FY2026. Net profit increased by 32.1% YoY to ₹3,650 crore driven by higher volumes and improved product mix. Net revenue grew 18.2% to ₹38,764 crore.',
    announcementDate: daysAgo(3),
    pdfUrl: 'https://nsearchives.nseindia.com/corporate/MARUTI_results_q2fy26.pdf',
    sourceUrl: 'https://www.nseindia.com/companies-listing/corporate-filings-announcements',
    isWatchlisted: false,
    read: false,
  },
  {
    id: 'mock-ann-009',
    exchange: 'BSE',
    scriptName: 'Sun Pharmaceutical Industries',
    scriptCode: '524715',
    category: 'Regulatory',
    subject: 'USFDA inspection outcome — Establishment Inspection Report received',
    description: 'Sun Pharmaceutical Industries Limited has received an Establishment Inspection Report (EIR) from the U.S. Food & Drug Administration (USFDA) for its Halol manufacturing facility, indicating that the inspection has been classified as Voluntary Action Indicated (VAI).',
    announcementDate: daysAgo(4),
    pdfUrl: null,
    sourceUrl: 'https://www.bseindia.com/corporates/ann.html',
    isWatchlisted: false,
    read: false,
  },
  {
    id: 'mock-ann-010',
    exchange: 'BSE',
    scriptName: 'Reliance Industries Ltd',
    scriptCode: '500325',
    category: 'Bonus/Split',
    subject: 'Sub-division of Equity Shares — Record Date Fixed',
    description: 'Reliance Industries Limited announces the sub-division/split of equity shares of the Company in the ratio of 1:2, i.e., each existing equity share of face value of ₹10/- shall be sub-divided into 2 equity shares of face value of ₹5/- each. Record date fixed as 28th October 2026.',
    announcementDate: daysAgo(5),
    pdfUrl: null,
    sourceUrl: 'https://www.bseindia.com/corporates/ann.html',
    isWatchlisted: true,
    read: true,
  },
  {
    id: 'mock-ann-011',
    exchange: 'NSE',
    scriptName: 'Hindustan Unilever Ltd',
    scriptCode: 'HINDUNILVR',
    category: 'Dividend',
    subject: 'Final Dividend of ₹24 per share recommended for FY2026',
    description: 'The Board of Directors of Hindustan Unilever Limited at its meeting held today has recommended a final dividend of ₹24/- per equity share of face value ₹1/- each for the financial year ended 31st March 2026, subject to approval of shareholders at the ensuing Annual General Meeting.',
    announcementDate: daysAgo(5),
    pdfUrl: null,
    sourceUrl: 'https://www.nseindia.com/companies-listing/corporate-filings-announcements',
    isWatchlisted: false,
    read: false,
  },
  {
    id: 'mock-ann-012',
    exchange: 'BSE',
    scriptName: 'HDFC Bank Ltd',
    scriptCode: '500180',
    category: 'Board Meeting',
    subject: 'Board approves issuance of Perpetual Additional Tier 1 Bonds',
    description: 'HDFC Bank Limited informs that the Board has approved the issuance of Perpetual Additional Tier 1 (AT1) bonds of ₹5,000 crore on private placement basis to eligible investors to augment its capital adequacy.',
    announcementDate: daysAgo(6),
    pdfUrl: null,
    sourceUrl: 'https://www.bseindia.com/corporates/ann.html',
    isWatchlisted: true,
    read: true,
  },
  {
    id: 'mock-ann-013',
    exchange: 'NSE',
    scriptName: 'Asian Paints Ltd',
    scriptCode: 'ASIANPAINT',
    category: 'Financial Results',
    subject: 'Q1 FY2026 Results — Revenue up 9% despite raw material pressure',
    description: 'Asian Paints Limited reported consolidated revenue from operations of ₹9,311 crore for Q1 FY2026, registering a growth of 9.1% YoY. EBITDA margin expanded by 120bps YoY to 21.3% on account of softening raw material prices.',
    announcementDate: daysAgo(7),
    pdfUrl: null,
    sourceUrl: 'https://www.nseindia.com/companies-listing/corporate-filings-announcements',
    isWatchlisted: false,
    read: false,
  },
  {
    id: 'mock-ann-014',
    exchange: 'BSE',
    scriptName: 'Wipro Ltd',
    scriptCode: '507685',
    category: 'Board Meeting',
    subject: 'Board Meeting to consider Buyback of equity shares',
    description: 'Wipro Limited has informed BSE that a meeting of the Board of Directors is scheduled to be held on 15th October 2026 to consider the proposal of buyback of fully paid-up equity shares of the Company from the open market through stock exchange mechanism.',
    announcementDate: daysAgo(7),
    pdfUrl: null,
    sourceUrl: 'https://www.bseindia.com/corporates/ann.html',
    isWatchlisted: true,
    read: false,
  },
  {
    id: 'mock-ann-015',
    exchange: 'NSE',
    scriptName: 'Infosys Ltd',
    scriptCode: 'INFY',
    category: 'AGM/EGM',
    subject: 'Outcome of Annual General Meeting held on 29th June 2026',
    description: 'Infosys Limited submits the outcome of the 43rd Annual General Meeting of the Company held on Saturday, 29th June 2026. All resolutions as set out in the Notice were passed with requisite majority.',
    announcementDate: daysAgo(10),
    pdfUrl: null,
    sourceUrl: 'https://www.nseindia.com/companies-listing/corporate-filings-announcements',
    isWatchlisted: true,
    read: true,
  },
]
